/*** Autogenerated by WIDL 1.6.1 from msdasc.idl - Do not edit ***/

#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif

#include <rpc.h>
#include <rpcndr.h>

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __msdasc_h__
#define __msdasc_h__

/* Forward declarations */

#ifndef __IDataInitialize_FWD_DEFINED__
#define __IDataInitialize_FWD_DEFINED__
typedef interface IDataInitialize IDataInitialize;
#endif

#ifndef __MSDAINITIALIZE_FWD_DEFINED__
#define __MSDAINITIALIZE_FWD_DEFINED__
#ifdef __cplusplus
typedef class MSDAINITIALIZE MSDAINITIALIZE;
#else
typedef struct MSDAINITIALIZE MSDAINITIALIZE;
#endif /* defined __cplusplus */
#endif /* defined __MSDAINITIALIZE_FWD_DEFINED__ */

/* Headers for imported files */

#include <oaidl.h>
#include <ocidl.h>
#include <oledb.h>

#ifdef __cplusplus
extern "C" {
#endif


DEFINE_GUID(LIBID_MSDASC, 0x2206ceb0, 0x19c1, 0x11d1, 0x89,0xe0, 0x00,0xc0,0x4f,0xd7,0xa8,0x29);

/*****************************************************************************
 * IDataInitialize interface
 */
#ifndef __IDataInitialize_INTERFACE_DEFINED__
#define __IDataInitialize_INTERFACE_DEFINED__

DEFINE_GUID(IID_IDataInitialize, 0x2206ccb1, 0x19c1, 0x11d1, 0x89,0xe0, 0x00,0xc0,0x4f,0xd7,0xa8,0x29);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("2206ccb1-19c1-11d1-89e0-00c04fd7a829")
IDataInitialize : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE GetDataSource(
        IUnknown *pUnkOuter,
        DWORD dwClsCtx,
        LPWSTR pwszInitializationString,
        REFIID riid,
        IUnknown **ppDataSource) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetInitializationString(
        IUnknown *pDataSource,
        boolean fIncludePassword,
        LPWSTR *ppwszInitString) = 0;

    virtual HRESULT STDMETHODCALLTYPE CreateDBInstance(
        REFCLSID clsidProvider,
        IUnknown *pUnkOuter,
        DWORD dwClsCtx,
        LPWSTR pwszReserved,
        REFIID riid,
        IUnknown **ppDataSource) = 0;

    virtual HRESULT STDMETHODCALLTYPE RemoteCreateDBInstanceEx(
        REFCLSID clsidProvider,
        IUnknown *pUnkOuter,
        DWORD dwClsCtx,
        LPWSTR pwszReserved,
        COSERVERINFO *pServerInfo,
        DWORD cmq,
        GUID **rgpIID,
        IUnknown **rgpItf,
        HRESULT *rghr) = 0;

    virtual HRESULT STDMETHODCALLTYPE LoadStringFromStorage(
        LPWSTR pwszFileName,
        LPWSTR *ppwszInitializationString) = 0;

    virtual HRESULT STDMETHODCALLTYPE WriteStringToStorage(
        LPWSTR pwszFileName,
        LPWSTR pwszInitializationString,
        DWORD dwCreationDisposition) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IDataInitialize, 0x2206ccb1, 0x19c1, 0x11d1, 0x89,0xe0, 0x00,0xc0,0x4f,0xd7,0xa8,0x29)
#endif
#else
typedef struct IDataInitializeVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IDataInitialize* This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IDataInitialize* This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IDataInitialize* This);

    /*** IDataInitialize methods ***/
    HRESULT (STDMETHODCALLTYPE *GetDataSource)(
        IDataInitialize* This,
        IUnknown *pUnkOuter,
        DWORD dwClsCtx,
        LPWSTR pwszInitializationString,
        REFIID riid,
        IUnknown **ppDataSource);

    HRESULT (STDMETHODCALLTYPE *GetInitializationString)(
        IDataInitialize* This,
        IUnknown *pDataSource,
        boolean fIncludePassword,
        LPWSTR *ppwszInitString);

    HRESULT (STDMETHODCALLTYPE *CreateDBInstance)(
        IDataInitialize* This,
        REFCLSID clsidProvider,
        IUnknown *pUnkOuter,
        DWORD dwClsCtx,
        LPWSTR pwszReserved,
        REFIID riid,
        IUnknown **ppDataSource);

    HRESULT (STDMETHODCALLTYPE *RemoteCreateDBInstanceEx)(
        IDataInitialize* This,
        REFCLSID clsidProvider,
        IUnknown *pUnkOuter,
        DWORD dwClsCtx,
        LPWSTR pwszReserved,
        COSERVERINFO *pServerInfo,
        DWORD cmq,
        GUID **rgpIID,
        IUnknown **rgpItf,
        HRESULT *rghr);

    HRESULT (STDMETHODCALLTYPE *LoadStringFromStorage)(
        IDataInitialize* This,
        LPWSTR pwszFileName,
        LPWSTR *ppwszInitializationString);

    HRESULT (STDMETHODCALLTYPE *WriteStringToStorage)(
        IDataInitialize* This,
        LPWSTR pwszFileName,
        LPWSTR pwszInitializationString,
        DWORD dwCreationDisposition);

    END_INTERFACE
} IDataInitializeVtbl;
interface IDataInitialize {
    CONST_VTBL IDataInitializeVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IDataInitialize_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IDataInitialize_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IDataInitialize_Release(This) (This)->lpVtbl->Release(This)
/*** IDataInitialize methods ***/
#define IDataInitialize_GetDataSource(This,pUnkOuter,dwClsCtx,pwszInitializationString,riid,ppDataSource) (This)->lpVtbl->GetDataSource(This,pUnkOuter,dwClsCtx,pwszInitializationString,riid,ppDataSource)
#define IDataInitialize_GetInitializationString(This,pDataSource,fIncludePassword,ppwszInitString) (This)->lpVtbl->GetInitializationString(This,pDataSource,fIncludePassword,ppwszInitString)
#define IDataInitialize_CreateDBInstance(This,clsidProvider,pUnkOuter,dwClsCtx,pwszReserved,riid,ppDataSource) (This)->lpVtbl->CreateDBInstance(This,clsidProvider,pUnkOuter,dwClsCtx,pwszReserved,riid,ppDataSource)
#define IDataInitialize_RemoteCreateDBInstanceEx(This,clsidProvider,pUnkOuter,dwClsCtx,pwszReserved,pServerInfo,cmq,rgpIID,rgpItf,rghr) (This)->lpVtbl->RemoteCreateDBInstanceEx(This,clsidProvider,pUnkOuter,dwClsCtx,pwszReserved,pServerInfo,cmq,rgpIID,rgpItf,rghr)
#define IDataInitialize_LoadStringFromStorage(This,pwszFileName,ppwszInitializationString) (This)->lpVtbl->LoadStringFromStorage(This,pwszFileName,ppwszInitializationString)
#define IDataInitialize_WriteStringToStorage(This,pwszFileName,pwszInitializationString,dwCreationDisposition) (This)->lpVtbl->WriteStringToStorage(This,pwszFileName,pwszInitializationString,dwCreationDisposition)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IDataInitialize_QueryInterface(IDataInitialize* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IDataInitialize_AddRef(IDataInitialize* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IDataInitialize_Release(IDataInitialize* This) {
    return This->lpVtbl->Release(This);
}
/*** IDataInitialize methods ***/
static FORCEINLINE HRESULT IDataInitialize_GetDataSource(IDataInitialize* This,IUnknown *pUnkOuter,DWORD dwClsCtx,LPWSTR pwszInitializationString,REFIID riid,IUnknown **ppDataSource) {
    return This->lpVtbl->GetDataSource(This,pUnkOuter,dwClsCtx,pwszInitializationString,riid,ppDataSource);
}
static FORCEINLINE HRESULT IDataInitialize_GetInitializationString(IDataInitialize* This,IUnknown *pDataSource,boolean fIncludePassword,LPWSTR *ppwszInitString) {
    return This->lpVtbl->GetInitializationString(This,pDataSource,fIncludePassword,ppwszInitString);
}
static FORCEINLINE HRESULT IDataInitialize_CreateDBInstance(IDataInitialize* This,REFCLSID clsidProvider,IUnknown *pUnkOuter,DWORD dwClsCtx,LPWSTR pwszReserved,REFIID riid,IUnknown **ppDataSource) {
    return This->lpVtbl->CreateDBInstance(This,clsidProvider,pUnkOuter,dwClsCtx,pwszReserved,riid,ppDataSource);
}
static FORCEINLINE HRESULT IDataInitialize_RemoteCreateDBInstanceEx(IDataInitialize* This,REFCLSID clsidProvider,IUnknown *pUnkOuter,DWORD dwClsCtx,LPWSTR pwszReserved,COSERVERINFO *pServerInfo,DWORD cmq,GUID **rgpIID,IUnknown **rgpItf,HRESULT *rghr) {
    return This->lpVtbl->RemoteCreateDBInstanceEx(This,clsidProvider,pUnkOuter,dwClsCtx,pwszReserved,pServerInfo,cmq,rgpIID,rgpItf,rghr);
}
static FORCEINLINE HRESULT IDataInitialize_LoadStringFromStorage(IDataInitialize* This,LPWSTR pwszFileName,LPWSTR *ppwszInitializationString) {
    return This->lpVtbl->LoadStringFromStorage(This,pwszFileName,ppwszInitializationString);
}
static FORCEINLINE HRESULT IDataInitialize_WriteStringToStorage(IDataInitialize* This,LPWSTR pwszFileName,LPWSTR pwszInitializationString,DWORD dwCreationDisposition) {
    return This->lpVtbl->WriteStringToStorage(This,pwszFileName,pwszInitializationString,dwCreationDisposition);
}
#endif
#endif

#endif

HRESULT STDMETHODCALLTYPE IDataInitialize_GetDataSource_Proxy(
    IDataInitialize* This,
    IUnknown *pUnkOuter,
    DWORD dwClsCtx,
    LPWSTR pwszInitializationString,
    REFIID riid,
    IUnknown **ppDataSource);
void __RPC_STUB IDataInitialize_GetDataSource_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer* pRpcChannelBuffer,
    PRPC_MESSAGE pRpcMessage,
    DWORD* pdwStubPhase);
HRESULT STDMETHODCALLTYPE IDataInitialize_GetInitializationString_Proxy(
    IDataInitialize* This,
    IUnknown *pDataSource,
    boolean fIncludePassword,
    LPWSTR *ppwszInitString);
void __RPC_STUB IDataInitialize_GetInitializationString_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer* pRpcChannelBuffer,
    PRPC_MESSAGE pRpcMessage,
    DWORD* pdwStubPhase);
HRESULT STDMETHODCALLTYPE IDataInitialize_CreateDBInstance_Proxy(
    IDataInitialize* This,
    REFCLSID clsidProvider,
    IUnknown *pUnkOuter,
    DWORD dwClsCtx,
    LPWSTR pwszReserved,
    REFIID riid,
    IUnknown **ppDataSource);
void __RPC_STUB IDataInitialize_CreateDBInstance_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer* pRpcChannelBuffer,
    PRPC_MESSAGE pRpcMessage,
    DWORD* pdwStubPhase);
HRESULT STDMETHODCALLTYPE IDataInitialize_RemoteCreateDBInstanceEx_Proxy(
    IDataInitialize* This,
    REFCLSID clsidProvider,
    IUnknown *pUnkOuter,
    DWORD dwClsCtx,
    LPWSTR pwszReserved,
    COSERVERINFO *pServerInfo,
    DWORD cmq,
    GUID **rgpIID,
    IUnknown **rgpItf,
    HRESULT *rghr);
void __RPC_STUB IDataInitialize_RemoteCreateDBInstanceEx_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer* pRpcChannelBuffer,
    PRPC_MESSAGE pRpcMessage,
    DWORD* pdwStubPhase);
HRESULT STDMETHODCALLTYPE IDataInitialize_LoadStringFromStorage_Proxy(
    IDataInitialize* This,
    LPWSTR pwszFileName,
    LPWSTR *ppwszInitializationString);
void __RPC_STUB IDataInitialize_LoadStringFromStorage_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer* pRpcChannelBuffer,
    PRPC_MESSAGE pRpcMessage,
    DWORD* pdwStubPhase);
HRESULT STDMETHODCALLTYPE IDataInitialize_WriteStringToStorage_Proxy(
    IDataInitialize* This,
    LPWSTR pwszFileName,
    LPWSTR pwszInitializationString,
    DWORD dwCreationDisposition);
void __RPC_STUB IDataInitialize_WriteStringToStorage_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer* pRpcChannelBuffer,
    PRPC_MESSAGE pRpcMessage,
    DWORD* pdwStubPhase);

#endif  /* __IDataInitialize_INTERFACE_DEFINED__ */

/*****************************************************************************
 * MSDAINITIALIZE coclass
 */

DEFINE_GUID(CLSID_MSDAINITIALIZE, 0x2206cdb0, 0x19c1, 0x11d1, 0x89,0xe0, 0x00,0xc0,0x4f,0xd7,0xa8,0x29);

#ifdef __cplusplus
class DECLSPEC_UUID("2206cdb0-19c1-11d1-89e0-00c04fd7a829") MSDAINITIALIZE;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(MSDAINITIALIZE, 0x2206cdb0, 0x19c1, 0x11d1, 0x89,0xe0, 0x00,0xc0,0x4f,0xd7,0xa8,0x29)
#endif
#endif

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __msdasc_h__ */
